development:
  adapter: postgresql
  encoding: unicode
  database: cable_0317
  pool: 5
  username: chenjian
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: loop2x_dev
  pool: 5
  username: chenjian
  password:
alicloud:
  adapter: postgresql
  encoding: unicode
  database: loop2x_dev
  pool: 5
  username: chenjian
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: loop2x_test
  pool: 5
  username: chenjian
  password: