common: &default_settings
  AppID: wx7e0701ab21a46321
  AppSecret: b62754c0d4578b20004f9a62666b8be9

production:
  <<: *default_settings


staging:
  <<: *default_settings


development:
  <<: *default_settings

test:
  <<: *default_settings